language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --features tar,zip
  - cargo test --features tar,zip
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
after_success:
- test $TRAVIS_BRANCH = "master" && bash ci/publish_docs.sh